include:
  # lynx aka urchin
  - board: nice_nano_v2
    shield: lynx_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: lynx_right
    snippet: studio-rpc-usb-uart

  # Helios aka kinesis adv2
  - board: blackpill_f411ce
    shield: helios
    snippet: studio-rpc-usb-uart

  # Selne aka Totem
  - board: seeeduino_xiao_ble
    shield: selene_left
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: selene_right
    snippet: studio-rpc-usb-uart

  # Celeste aka Keychron Q8
  - board: celeste

  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
