include:
  # Selne aka Totem
  - board: seeeduino_xiao_ble
    shield: selene_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: selene_left rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: selene_right rgbled_adapter
    snippet: studio-rpc-usb-uart

  # firmware reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
