include:
  # Selne aka Totem
  - board: seeeduino_xiao_ble
    shield: selene_dongle dongle_screen
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: selene_dongle dongle_screen
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: selene_left rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: selene_right rgbled_adapter
    snippet: studio-rpc-usb-uart

  # Themis aka Standalon Totem
  - board: seeeduino_xiao_ble
    shield: selene_left rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_KEYBOARD_NAME=\"themis\" -DCONFIG_ZMK_STUDIO=y
    artifact-name: themis_left
  - board: seeeduino_xiao_ble
    shield: selene_right rgbled_adapter
    snippet: studio-rpc-usb-uart
    artifact-name: themis_right

  # calypso aka skeletyl
  - board: nice_nano_v2
    shield: calypso_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: calypso_right
    snippet: studio-rpc-usb-uart

  # firmware reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
