include:
  # calypso aka corne
  - board: nice_nano_v2
    shield: calypso_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: calypso_right
    snippet: studio-rpc-usb-uart

  # Helios aka kinesis adv2
  - board: blackpill_f411ce
    shield: helios
    snippet: studio-rpc-usb-uart

  # Keychron Q8
  - board: keychron_q8

  - board: nice_nano_v2
    shield: settings_reset
