CONFIG_RGBLED_WIDGET_BATTERY_SHOW_SELF=y

# Power Management
CONFIG_ZMK_SLEEP=y

CONFIG_DONGLE_SCREEN_FLIPPED=y
CONFIG_DONGLE_SCREEN_AMBIENT_LIGHT=y
CONFIG_DONGLE_SCREEN_IDLE_TIMEOUT_S=0
CONFIG_DONGLE_SCREEN_MAX_BRIGHTNESS=75

CONFIG_ZMK_STUDIO=y
