name: Build ZMK Firmware

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  # credits: BerkeleyTrue/zmk-keyboards
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: firmware

      - name: Generate Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          name: ${{ github.ref_name || "Latest ZMK Firmware" }}
          tag_name: ${{ github.ref_name || 'latest' }}
          fail_on_unmatched_files: false
          draft: false
          prerelease: false
          files: |
            firmware/*.hex
            firmware/*.bin
            firmware/*.uf2
